# Generated by Django 4.1.1 on 2022-09-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="blog_post_publish_c4286e_idx",
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-publish"], name="blog_post_publish_bb7600_idx"
            ),
        ),
    ]
