# Generated by Django 4.1.1 on 2022-09-22 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment_comment_blog_commen_created_0e6ed4_idx"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="update",
            new_name="updated",
        ),
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
